### ISSUE TITLE
Bump `cookie` to v0.7.0

### ISSUE THREAD

**Issue by ivasilov** [bundled-es-modules/cookie#2]
There was a [vulnerability](https://github.com/jshttp/cookie/pull/167) which was fixed in v0.7.0. Since this library depends on `cookie` and has strict version range, it can't be updated to 0.7.0.

**Comment by Eric-Arellano** [comment]
Thank you for fixing this! Any ETA on a release to NPM?

**Comment by kettanaito** [comment]
@Eric-Arellano, I've opened a pull request to add release automation to this package (see #4). If we get it merged, I will see the release to NPM. All the following releases will be published automatically on merge to `main`.

**Comment by jpreynat** [comment]
@thepassle Any chance to get a new version of this module on npm that includes this fix? 🙏 
Thanks in advance!

**Comment by RomeoDespres** [comment]
For anyone trying to fix the recent security issue - just found out you can add the following to `package.json`:

```json
"overrides": {
    "@bundled-es-modules/cookie": {
      "cookie": ">=0.7.0"
    }
  }
```

which will force installation of the patched version of `cookie` - and likely won't break anything since this package does not depend on any feature of `cookie`.
